# http://symfony.com/doc/current/book/security.html
security:
    providers:
        user:
            entity: { class: App\Entity\User, property: email }
        admin:
            entity: { class: App\Entity\Admin, property: email }
    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 15
        App\Entity\Admin:
            algorithm: auto
            cost: 15
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|img|js)/
            security: false
        admin:
            pattern: ^(/$|/user|/admin_74ze5f|/home/|/home$)
            provider: admin
            anonymous: ~
            logout:
                invalidate_session: true
                path: /admin_74ze5f/logout
                target: /
            switch_user: true
            guard:
                authenticators:
                    - App\Security\Guard\AdminLoginAuthenticator
    access_control:
        - { path: ^/admin_74ze5f/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin_74ze5f/, role: ROLE_SUPER_ADMIN }
        - { path: ^/user/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, roles: [ROLE_USER, ROLE_SUPER_ADMIN] }